kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    kind: KubeletConfiguration
    maxPods: 300
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30428
        hostPort: 8428
        protocol: TCP
      - containerPort: 30300
        hostPort: 3000
        protocol: TCP
