apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-verifier
  namespace: monitoring
  labels:
    app: log-verifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-verifier
  template:
    metadata:
      labels:
        app: log-verifier
    spec:
      containers:
        - name: log-verifier
          image: log-verifier:latest
          imagePullPolicy: IfNotPresent
          args:
            - -victoriaLogsAddr=http://vls-victoria-logs-single-server-0.vls-victoria-logs-single-server.monitoring.svc.cluster.local.:9428
          ports:
            - containerPort: 8080
              name: http
