apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: log-verifier
  namespace: monitoring
spec:
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - port: http
      scheme: http
      interval: 10s
  selector:
    matchLabels:
      app: log-verifier
